services:
  - type: web
    name: WindGuard
    env: python
    # Указываем версию Python, которую нужно использовать
    pythonVersion: 3.11.9 
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn erosion_project.wsgi --timeout 120"